import type { RealmDef } from '../game/types'

// itemDrop / materialDrop are base weights (0.012 = 1.2%).
// Final gear chance is also scaled by the player's Item Drop stat.
export const realms: RealmDef[] = [
  {
    id: 1,
    name: 'Forgotten Crossroads',
    blurb: 'Dusty ways where lesser relics first stir.',
    image: '/realms/forgotten-crossroads.jpg',
    theme: { from: '#4a3318', to: '#120e0a', accent: '#d6a15a' },
    monsters: [
      {
        id: 'dust-mite',
        name: 'Dust Mite',
        image: '/monsters/dust-mite.png',
        hp: 110,
        attack: 14,
        defense: 6,
        xp: 10,
        gold: 3,
        progress: 55,
        itemDrop: 0.012,
        materialDrop: 0.14,
      },
      {
        id: 'road-gnoll',
        name: 'Road Gnoll',
        image: '/monsters/road-gnoll.png',
        hp: 155,
        attack: 17,
        defense: 9,
        xp: 20,
        gold: 4,
        progress: 62,
        itemDrop: 0.014,
        materialDrop: 0.13,
      },
      {
        id: 'lost-shade',
        name: 'Lost Shade',
        image: '/monsters/lost-shade.png',
        hp: 140,
        attack: 22,
        defense: 7,
        xp: 30,
        gold: 4,
        progress: 68,
        itemDrop: 0.015,
        materialDrop: 0.12,
      },
      {
        id: 'waystone-brute',
        name: 'Waystone Brute',
        image: '/monsters/waystone-brute.png',
        hp: 240,
        attack: 26,
        defense: 16,
        xp: 40,
        gold: 7,
        progress: 80,
        itemDrop: 0.018,
        materialDrop: 0.16,
      },
    ],
  },
  {
    id: 2,
    name: 'Sunken Catacombs',
    blurb: 'Waterlogged tombs stacked with forgotten steel.',
    image: '/realms/sunken-catacombs.jpg',
    theme: { from: '#16363a', to: '#071016', accent: '#5eead4' },
    monsters: [
      {
        id: 'bone-crawler',
        name: 'Bone Crawler',
        image: '/monsters/bone-crawler.png',
        hp: 320,
        attack: 32,
        defense: 18,
        xp: 14,
        gold: 9,
        progress: 48,
        itemDrop: 0.016,
        materialDrop: 0.15,
      },
      {
        id: 'drowned-acolyte',
        name: 'Drowned Acolyte',
        image: '/monsters/drowned-acolyte.png',
        hp: 380,
        attack: 40,
        defense: 16,
        xp: 17,
        gold: 11,
        progress: 54,
        itemDrop: 0.018,
        materialDrop: 0.14,
      },
      {
        id: 'crypt-guard',
        name: 'Crypt Guard',
        image: '/monsters/crypt-guard.png',
        hp: 480,
        attack: 36,
        defense: 28,
        xp: 20,
        gold: 13,
        progress: 60,
        itemDrop: 0.02,
        materialDrop: 0.17,
      },
      {
        id: 'vault-wraith',
        name: 'Vault Wraith',
        image: '/monsters/vault-wraith.png',
        hp: 430,
        attack: 48,
        defense: 18,
        xp: 24,
        gold: 12,
        progress: 68,
        itemDrop: 0.022,
        materialDrop: 0.13,
      },
    ],
  },
  {
    id: 3,
    name: 'Ember Peaks',
    blurb: 'Ash-choked ridges where relics still burn.',
    image: '/realms/ember-peaks.jpg',
    theme: { from: '#5a1c12', to: '#140807', accent: '#fb923c' },
    monsters: [
      {
        id: 'cinder-wolf',
        name: 'Cinder Wolf',
        image: '/monsters/cinder-wolf.png',
        hp: 620,
        attack: 52,
        defense: 26,
        xp: 28,
        gold: 18,
        progress: 42,
        itemDrop: 0.02,
        materialDrop: 0.16,
      },
      {
        id: 'magma-scarab',
        name: 'Magma Scarab',
        image: '/monsters/magma-scarab.png',
        hp: 780,
        attack: 48,
        defense: 42,
        xp: 32,
        gold: 20,
        progress: 48,
        itemDrop: 0.022,
        materialDrop: 0.18,
      },
      {
        id: 'peak-raider',
        name: 'Peak Raider',
        image: '/monsters/peak-raider.png',
        hp: 720,
        attack: 62,
        defense: 30,
        xp: 36,
        gold: 24,
        progress: 54,
        itemDrop: 0.024,
        materialDrop: 0.15,
      },
      {
        id: 'ember-tyrant',
        name: 'Ember Tyrant',
        image: '/monsters/ember-tyrant.png',
        hp: 980,
        attack: 72,
        defense: 38,
        xp: 45,
        gold: 30,
        progress: 64,
        itemDrop: 0.028,
        materialDrop: 0.2,
      },
    ],
  },
]
